### ISSUE TITLE
求不要阉割<!--more-->标签！！

### ISSUE THREAD

**Issue by netcan** [unhealthy/hexo-all-minifier#1]
求不要阉割标签！！

**Comment by unhealthy** [comment]
我瞅瞅...这个应该要改htmlminifier

**Comment by unhealthy** [comment]
fix 了，你试试看

**Comment by netcan** [comment]
。。恩，发现新问题。。</html>会出现在</head>后面而不是文档最后面。。

**Comment by netcan** [comment]
。。恩，发现新问题。。</html>会出现在</head>后面而不是文档最后面。。

**Comment by unhealthy** [comment]
好的，我看看

**Comment by unhealthy** [comment]
@netcan 我这好像并没有遇到这个情况喔，你能否提供更多的信息呢？

**Comment by netcan** [comment]
应该是我主题问题，我开了removeOptiontag了去掉</html>了。。反正不影响使用，谢谢了。。

**Comment by unhealthy** [comment]
ok
