### ISSUE TITLE
Only Minifies post content.

### ISSUE THREAD

**Issue by matthewsanders** [unhealthy/hexo-all-minifier#10]
I was using hexo-html-minifier on hexo 3.1.1 which would work great on the full page.  I later upgraded to hexo 3.2.0 which broke this behavior and only minified the post content under `<div class="article-entry" itemprop="articleBody">`.

I decided to install hexo-all-minifier to see if that would work and I end up with the same result.  

It would appear that hexo 3.2.0 may have universally broken both minifiers, probably due to either an order of operations change or limiting content processed by the generators.

**Comment by matthewsanders** [comment]
Apparently this has been fixed in hexo AFTER 3.2.0.  The git sha: `95fb3ce22621bc477e48adfec4152696eb1aae29`

So if you currently need this fix you can uninstall hexo from npm and reinstall with git:

`npm install //git@github.com:hexojs/hexo.git --save`

**Comment by unhealthy** [comment]
thanks for your feedback!
