### ISSUE TITLE
html没有压缩，其他都ok

### ISSUE THREAD

**Issue by 52cik** [unhealthy/hexo-all-minifier#6]
我用默认配置的，但是html没有压缩，会不会是 hexo 新版本的问题？
我测试 hexo-html-minifier 也是没法压缩。

**Comment by unhealthy** [comment]
请问你的hexo的版本是？

**Comment by 52cik** [comment]
3.2.0
前天更新了下，发现好多东西不能用了。

**Comment by unhealthy** [comment]
好的，我今晚看看~

**Comment by unhealthy** [comment]
@52cik  https://github.com/hexojs/hexo/issues/1793
看一下这个issue，好像新版本有个bug，我也没法编译了，用3.2的话
目前好像还没有解决的方法

**Comment by 52cik** [comment]
好吧，只能等 hexo 修复了。。
